server:
  port: 8091

spring:
  application:
    name: gestion-zoologico
  datasource:
    url: ${DB_URL}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${KEYSECRET_SECURITY}
  expiration: ${EXPIRE_MS_SECURITY}

management:
  endpoints:
    web:
      exposure:
        include: "*"

cloud:
  aws:
    stack:
      auto: false   # evita que intente detectar automáticamente el stack de CloudFormation
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

scheduler:
  excel-cron: ${EXCEL_CRON}
  pdf-cron: ${PDF_CRON}


appDescription: "zoologico-service"
appVersion: "1.0.0"
