server:
  port: 8091

spring:
  application:
    name: gestion-zoologico
  datasource:
    url: ${DB_URL}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${KEYSECRET_SECURITY}
  expiration: ${EXPIRE_MS_SECURITY}


management:
  endpoints:
    web:
      exposure:
        include: "*"
appDescription: "gestion-zoologico"
appVersion: "1.0.0"