server:
  port: 8092

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

security:
  jwt:
    secret: ${KEYSECRET_SECURITY}   # <- Variable de entorno
    issuer: "zoologico-service"
    audience: "messaging-service"

appDescription: "Messaging-Service"
appVersion: "1.0.0"
